site_name: PPS Unidad 1 - Tarea RA1 - Carlos Castillo

nav:
  - Inicio: index.md
  - Elementos de Python: python.md
  - Ejecuci贸n y Depuraci贸n: ejecucion.md
  - Pruebas: pruebas.md
  - Ejecuci贸n en Sandbox: sandbox.md
  - Reflexi贸n: reflexion.md

theme:
  name: material
  palette:
    scheme: slate
